### PR TITLE
Quick fixes for dashboard

### LINKED ISSUE #49: Dashboard clean-up
A few things might make it easier to use the dashboard notebook:

1. rather than separate sections for looking at local data, use an `if` block to set `paths` to either the `/glade/` location or the `webext` web site (perhaps this could be based on if `os.ispath("/glade/work/")`)
2. Move the panel info to a YAML file so that adding additional tabs to the dashboard does not require modifying the notebook itself
3. drop the blue bar with icons / menu text

### PR DESCRIPTION
**Pull request by mnlevy1981**
No need for separate sections of the notebook for glade and webext; also clean up the dashboard itself: remove blue side panel, and move some of the dashboard setup code to a YAML file.

Fixes #49

### CODE REVIEW

**Comment by mnlevy1981** [comment]
I'll take this out of draft mode when all three components of the issue are addressed

**Comment by mnlevy1981** [comment]
I updated the documentation inside this notebook; should I also update the top-level `README` (i.e. also fix #48)?

**Review by mgrover1 — APPROVED** [review]
This looks great - we can add the documentation to the README in another PR...

**Comment by mgrover1** [comment]
@mnlevy1981 feel free to merge when you are ready!

**Pull request merged**
