### PR TITLE
add surface Chl and macronutrient plots to plot_suite notebooks

### PR DESCRIPTION
**Pull request by klindsay28**
rerun plot_suite notebooks

add .isel_dict to variable metadata and apply when selecting DataArray from Dataset

### CODE REVIEW

**Comment by klindsay28** [comment]
This is not ready to merge. I'm working on adding plots of multiple vertical levels of macronutrients.

**Comment by klindsay28** [comment]
There are now subsurface plots of O2 and macronutrients.

The notebooks are getting large in size. The 003 and 004 notebooks are 51 and 47 Megabytes respectively. The 003 notebook generates the following warning from github:
```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File notebooks/plot_suite_003.ipynb is 50.81 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

One way to reduce this would be to use @matt-long's papermill idea to generate one notebook per diagnostic. This could also enable parallel generation of these notebooks, making it quicker to generate them. I think this is beyond the scope of this PR.

**Comment by dcherian** [comment]
Maybe it's worth trying https://ipynbcompress.readthedocs.io/en/latest/index.html to compress the images?

**Comment by klindsay28** [comment]
@dcherian, I take the large size of the notebook files as a sign that there are too many figures in the notebook.

<gripe mode>
I am not a fan of having hundreds of images strung across a long notebook. It feels like a poor way of organizing a large amount of content. I end up doing lots of scrolling to find particular content and find this very inefficient. 
</gripe mode>

What I would really like is a decent way to organize this large amount of content that makes it easier to access it. But I don't know how do that with notebooks.

**Comment by matt-long** [comment]
Looping @andersy005 in here. I think we need to scope out some possible design solutions:
- Use papermill to parameterize and run the same notebook on different variables: leads to a lot of output notebooks; we need a sensible way to organize this content, perhaps in a sphinx page
- Use a holoview or similar widget to enable selection of what to view within a common interface

**Comment by dcherian** [comment]
Perhaps notebooks are not the solution here --- these notebooks have no text...

How about some kind of "image browser" that takes as input a folder and a filename schema e.g. ``{{variable}}_{{depthlevel}}_{{time}}.png`` and then offered selection by ``variable`` ``depthlevel`` and ``time``. 

How do we expect to "consume" these images?

1. There's probably some way to make https://napari.org/ do this if we wanted an application interface that runs locally
2. We could use some holoviews thing; but this requires a python process (AFAIK) and so would again be run locally
3. There's probably a javascript thing that would run in the browser; this would work for a publicly accessible website.

Another advantage of the "image browser" idea is that it's quite easy to generate images in parallel using `xr.map_blocks`

**Comment by klindsay28** [comment]
@dcherian, there's little text in the note because I decided to loop over all diagnostics listed in a yaml file, instead of listing the diagnostics terms in the notebook. It doesn't seem possible to split a loop in a notebook across cells, so I don't see how to get text cells between plots, much less groups of plots.

I'm all ears for better ways of organizing this content. I'm not familiar enough with the suggested tools to be able to comment on their strengths and/or weaknesses.

One feature that I'd like to see in a reorganization is the ability to look at maps of different variables for the same month side-by-side. For example, I'd like to be to examine `photoC_diat_zint` and `photoC_cocco_zint` side-by-side for a particular month to be able to see how spatial patterns of these different fields correspond to each other. The current notebook layout doesn't make this easy. The only way I see to do that now is to open the notebook in multiple taps and scroll to different points in the notebook. I find this clumsy.

**Pull request merged**
