### PR TITLE
updated environment file

### PR DESCRIPTION
**Pull request by matt-long**
This PR includes additional packages that are likely to be useful in analysis. 

While I appreciate the effort to delineate dependencies into categories, I find that in practice it's much easier to simply have an alphabetized list; this enable determining at a glance whether a particular package is included or not.

@andersy005, can you please review to make sure we're not missing anything essential or if we might need to pin any versions.

### CODE REVIEW

**Comment by matt-long** [comment]
@mnlevy1981, black is complaining here about files I did not touch.

**Comment by mnlevy1981** [comment]
> @mnlevy1981, black is complaining here about files I did not touch.

I think `black` recently released v20, and it has slightly different expectations than v19... I ran into something similar in [pop-tools](https://github.com/NCAR/pop-tools/commit/8582dd08236a6807bc574192ad8fbf909779c2d2); thanks for the heads up, I'll get it fixed on `master`

**Comment by andersy005** [comment]
> I think black recently released v20, and it has slightly different expectations than v19... I ran into something similar in pop-tools; thanks for the heads up, I'll get it fixed on master

To keep everything in sync, we could replace the existing `black` GitHub action with the `pre-commit` hook check GitHub action. This guarantees that the settings and versions used by pre-commit hooks are the same as the ones used in the CI:



`linting.yaml`:

```yaml
name: linting

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
```

It makes sense to add the above changes to #17.

**Comment by matt-long** [comment]
That's a good point. 

@mnlevy1981, I'll let you merge when you're ready.

**Pull request merged**
